#pragma once

#include "L3DRenderUnit.h"

#include "FX11/inc/d3dx11effect.h"

struct L3D_EFFECT_TABLE
{
	struct _EFFECT_INFO
	{
		ID3DX11Effect* pEffect;
		ID3DX11EffectTechnique* pEffectTech;
		ID3DX11EffectMatrixVariable* pWorldViewProj;
		ID3D11InputLayout* pLayout;

	} Table[L3D_SHADER_EFFECT_COUNT];
};

struct _SHADER_EFFECT_INFO
{
	L3D_SHADER_EFFECT eShaderEffect;
	const char* szTechName;
	const char* szMaxtrixName;
	unsigned uDescCount;
	D3D11_INPUT_ELEMENT_DESC DescArr[30];
};

static const _SHADER_EFFECT_INFO SHADER_EFFECT_LIST[] =
{
	{
		L3D_SHADER_EFFECT_BOX,
		"ColorTech",
		"gWorldViewProj",
		2,
		{
			{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT,    0, 0 , D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
		}
	},
	{
		L3D_SHADER_EFFECT_CI_SKINMESH,
		"ColorTech",
		"gWorldViewProj",
		7,
		{
			{"POSITION",    0, DXGI_FORMAT_R32G32B32_FLOAT,     0,  D3D11_APPEND_ALIGNED_ELEMENT,   D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"NORMAL",      0, DXGI_FORMAT_R32G32B32_FLOAT,     0,  D3D11_APPEND_ALIGNED_ELEMENT,   D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"COLOR",       0, DXGI_FORMAT_R32G32B32A32_FLOAT,  0,  D3D11_APPEND_ALIGNED_ELEMENT,   D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TEXCOORD",    0, DXGI_FORMAT_R32G32_FLOAT,        0,  D3D11_APPEND_ALIGNED_ELEMENT,   D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"BONEWEIGHTS", 0, DXGI_FORMAT_R32G32B32A32_FLOAT,  0,  D3D11_APPEND_ALIGNED_ELEMENT,   D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"BONEINDICES", 0, DXGI_FORMAT_R8G8B8A8_UINT,       0,  D3D11_APPEND_ALIGNED_ELEMENT,   D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TANGENT",     0, DXGI_FORMAT_R32G32B32A32_FLOAT,  0,  D3D11_APPEND_ALIGNED_ELEMENT,   D3D11_INPUT_PER_VERTEX_DATA, 0}
		}
	},
};

L3D_EFFECT_TABLE* CreateEffectTable(ID3D11Device* piDevice);